{% set name = "fdtd" %}
{% set version = "0.3.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 714694f4faa1206f2252fe41a4d67aa076ce32ba2ae458bb23e59c756b28e9cf

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - scipy
    - tqdm

test:
  imports:
    - fdtd
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/flaport/fdtd
  summary: a 3D electromagnetic FDTD simulator written in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - flaport
